apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artifactory
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: artifactory
    spec:
      containers:
        - image: amesken/artifactory
          name: artifactory
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /artifactory/data
              name: artifactory-claim0
            - mountPath: /artifactory/logs
              name: artifactory-claim1
            - mountPath: /artifactory/backup
              name: artifactory-claim2
      restartPolicy: Always
      volumes:
        - name: artifactory-claim0
          persistentVolumeClaim:
            claimName: artifactory-claim0
        - name: artifactory-claim1
          persistentVolumeClaim:
            claimName: artifactory-claim1
        - name: artifactory-claim2
          persistentVolumeClaim:
            claimName: artifactory-claim2
status: {}
