apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: gitlab
    spec:
      containers:
        - env:
            - name: GITLAB_BACKUPS
              value: daily
            - name: GITLAB_BACKUP_TIME
              value: "01:00"
            - name: GITLAB_EMAIL
              value: meskena@gmail.com
            - name: GITLAB_EMAIL_REPLY_TO
              value: cdtoolstack@gmail.com
            - name: GITLAB_HOST
              value: 192.168.99.100
            - name: GITLAB_INCOMING_EMAIL_ADDRESS
              value: meskena@gmail.com
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: "true"
            - name: GITLAB_NOTIFY_PUSHER
              value: "false"
            - name: GITLAB_PORT
              value: "10080"
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: long-and-random-alphanumeric-string
            - name: GITLAB_SSH_PORT
              value: "10022"
            - name: GITLAB_TIMEZONE
              value: Amsterdam
            - name: IMAP_ENABLED
              value: "false"
            - name: IMAP_HOST
              value: imap.gmail.com
            - name: IMAP_PASS
              value: password
            - name: IMAP_PORT
              value: "993"
            - name: IMAP_SSL
              value: "true"
            - name: IMAP_STARTTLS
              value: "false"
            - name: IMAP_USER
              value: mailer@example.com
            - name: SMTP_AUTHENTICATION
              value: login
            - name: SMTP_DOMAIN
              value: www.example.com
            - name: SMTP_ENABLED
              value: "false"
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PASS
              value: password
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_STARTTLS
              value: "true"
            - name: SMTP_USER
              value: mailer@example.com
            - name: TZ
              value: Europe/Amsterdam
          image: sameersbn/gitlab:8.0.3
          name: gitlab
          ports:
            - containerPort: 80
            - containerPort: 22
          resources: {}
          volumeMounts:
            - mountPath: /home/git/data
              name: gitlab-claim0
      restartPolicy: Always
      volumes:
        - name: gitlab-claim0
          persistentVolumeClaim:
            claimName: gitlab-claim0
status: {}
