apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nodefirefox
  name: nodefirefox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodefirefox
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nodefirefox
    spec:
      containers:
        - image: selenium/node-firefox-debug
          name: nodefirefox
          ports:
            - containerPort: 5900
          resources: {}
      restartPolicy: Always
status: {}
